a=int(input("enter number 1"))#10
b=int(input("enter number 2"))#20
c=int(input("enter numbr 3"))#30
if(a>b and a>c):
    print("a is greatest")
if(b>a and b>c):
    print("b is greatest")
if(c>a and c>b):
    print("c is greatest")        